mapper:
  scatter_radius: 1.0
  nms_radius: 0.4
  eig_ratio_32: 0.65
  eig_ratio_21: 0.65
  min_neighbor_count: 5
  voxel_size: 0.2
  scan_tf:
    position: [0, 0, 0] # position in base frame
    orientation: [0, 0, 0, 1] # orientation in base frame
  kdtree_search_radius: 0.85
fast_slam:
  max_feature_range: 12 # [m]
  max_unobserved_count: -10 # remove landmark after unobserved this often
  particle_count: 100
  keypoint_covariance: [0.6, 0, 0, 0, 0.6, 0, 0, 0, 0.6]
  observation_covariance: [0.4, 0, 0, 0, 0.2, 0, 0, 0, 0.2]
motion_model_gp:
  model_dir: "/path/to/model_dir/"
  estimated_motion_labels:
    x: "gp_label_x"
    y: "gp_label_y"
    theta: "gp_label_theta"
  previous_motion_labels:
    x: "gp_label_x"
    y: "gp_label_y"
    theta: "gp_label_theta"
  bag_runner:
    bag_path: "/path/to/rosbag"
    estimated_odometry_topic: "/odom" # estimated odometry
    pointcloud_topic: "/velodyne_points" # 3D scan
    groundtruth_topic: "/ground_truth/odom" # ground truth odometry
    sync_period: 0.1 # [sec.]
    stop_after: -1 # will end after this many iterations

